version: '3.9'


services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/aprems
      - ./staticfiles:/aprems/staticfiles
      - ./media:/aprems/media
      - ./db.sqlite3:/aprems/db.sqlite3  # Ensure SQLite DB persists
